apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
  namespace: default
spec:
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - image: registry-vpc.cn-beijing.aliyuncs.com/moseeker/python-docker:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: python-demo
        env:
        - name: branch
          value: <BRANCH_NAME>
